// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConfirmSubscriptionHandlerFunc turns a function with the right signature into a confirm subscription handler
type ConfirmSubscriptionHandlerFunc func(ConfirmSubscriptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ConfirmSubscriptionHandlerFunc) Handle(params ConfirmSubscriptionParams) middleware.Responder {
	return fn(params)
}

// ConfirmSubscriptionHandler interface for that can handle valid confirm subscription params
type ConfirmSubscriptionHandler interface {
	Handle(ConfirmSubscriptionParams) middleware.Responder
}

// NewConfirmSubscription creates a new http.Handler for the confirm subscription operation
func NewConfirmSubscription(ctx *middleware.Context, handler ConfirmSubscriptionHandler) *ConfirmSubscription {
	return &ConfirmSubscription{Context: ctx, Handler: handler}
}

/*
	ConfirmSubscription swagger:route GET /confirm/{token} subscription confirmSubscription

# Confirm email subscription

Confirms a subscription using the token sent in the confirmation email.
*/
type ConfirmSubscription struct {
	Context *middleware.Context
	Handler ConfirmSubscriptionHandler
}

func (o *ConfirmSubscription) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewConfirmSubscriptionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
