// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subscription.sql

package db

import (
	"context"
)

const insertSubscription = `-- name: InsertSubscription :one
INSERT INTO subscriptions (email, city, frequency, token)
VALUES ($1, $2, $3, uuid_generate_v4())
RETURNING id, email, city, frequency, token, confirmed
`

type InsertSubscriptionParams struct {
	Email     string        `json:"email"`
	City      string        `json:"city"`
	Frequency FrequencyEnum `json:"frequency"`
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, insertSubscription, arg.Email, arg.City, arg.Frequency)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.City,
		&i.Frequency,
		&i.Token,
		&i.Confirmed,
	)
	return i, err
}
