// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Weather Forecast API
//
//	Weather API application that allows users to subscribe to weather updates for their city.
//	Schemes:
//	  http
//	  https
//	Host: weatherapi.app
//	BasePath: /api
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - application/x-www-form-urlencoded
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
