// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc_create_subscription.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Frequency     Frequency              `protobuf:"varint,3,opt,name=frequency,proto3,enum=pb.Frequency" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_rpc_create_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetFrequency() Frequency {
	if x != nil {
		return x.Frequency
	}
	return Frequency_FREQUENCY_UNSPECIFIED
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_rpc_create_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

var File_rpc_create_subscription_proto protoreflect.FileDescriptor

const file_rpc_create_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1drpc_create_subscription.proto\x12\x02pb\x1a\x12subscription.proto\"r\n" +
	"\x19CreateSubscriptionRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12+\n" +
	"\tfrequency\x18\x03 \x01(\x0e2\r.pb.FrequencyR\tfrequency\"R\n" +
	"\x1aCreateSubscriptionResponse\x124\n" +
	"\fsubscription\x18\x01 \x01(\v2\x10.pb.SubscriptionR\fsubscriptionB'Z%github.com/kirildevops/weather-api/pbb\x06proto3"

var (
	file_rpc_create_subscription_proto_rawDescOnce sync.Once
	file_rpc_create_subscription_proto_rawDescData []byte
)

func file_rpc_create_subscription_proto_rawDescGZIP() []byte {
	file_rpc_create_subscription_proto_rawDescOnce.Do(func() {
		file_rpc_create_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_subscription_proto_rawDesc), len(file_rpc_create_subscription_proto_rawDesc)))
	})
	return file_rpc_create_subscription_proto_rawDescData
}

var file_rpc_create_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_subscription_proto_goTypes = []any{
	(*CreateSubscriptionRequest)(nil),  // 0: pb.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil), // 1: pb.CreateSubscriptionResponse
	(Frequency)(0),                     // 2: pb.Frequency
	(*Subscription)(nil),               // 3: pb.Subscription
}
var file_rpc_create_subscription_proto_depIdxs = []int32{
	2, // 0: pb.CreateSubscriptionRequest.frequency:type_name -> pb.Frequency
	3, // 1: pb.CreateSubscriptionResponse.subscription:type_name -> pb.Subscription
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_create_subscription_proto_init() }
func file_rpc_create_subscription_proto_init() {
	if File_rpc_create_subscription_proto != nil {
		return
	}
	file_subscription_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_subscription_proto_rawDesc), len(file_rpc_create_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_subscription_proto_goTypes,
		DependencyIndexes: file_rpc_create_subscription_proto_depIdxs,
		MessageInfos:      file_rpc_create_subscription_proto_msgTypes,
	}.Build()
	File_rpc_create_subscription_proto = out.File
	file_rpc_create_subscription_proto_goTypes = nil
	file_rpc_create_subscription_proto_depIdxs = nil
}
