// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc_get_weather.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherRequest) Reset() {
	*x = GetWeatherRequest{}
	mi := &file_rpc_get_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherRequest) ProtoMessage() {}

func (x *GetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weather       *Weather               `protobuf:"bytes,1,opt,name=weather,proto3" json:"weather,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherResponse) Reset() {
	*x = GetWeatherResponse{}
	mi := &file_rpc_get_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherResponse) ProtoMessage() {}

func (x *GetWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherResponse) GetWeather() *Weather {
	if x != nil {
		return x.Weather
	}
	return nil
}

var File_rpc_get_weather_proto protoreflect.FileDescriptor

const file_rpc_get_weather_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_get_weather.proto\x12\x02pb\x1a\rweather.proto\"'\n" +
	"\x11GetWeatherRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\";\n" +
	"\x12GetWeatherResponse\x12%\n" +
	"\aweather\x18\x01 \x01(\v2\v.pb.WeatherR\aweatherB'Z%github.com/kirildevops/weather-api/pbb\x06proto3"

var (
	file_rpc_get_weather_proto_rawDescOnce sync.Once
	file_rpc_get_weather_proto_rawDescData []byte
)

func file_rpc_get_weather_proto_rawDescGZIP() []byte {
	file_rpc_get_weather_proto_rawDescOnce.Do(func() {
		file_rpc_get_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_weather_proto_rawDesc), len(file_rpc_get_weather_proto_rawDesc)))
	})
	return file_rpc_get_weather_proto_rawDescData
}

var file_rpc_get_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_weather_proto_goTypes = []any{
	(*GetWeatherRequest)(nil),  // 0: pb.GetWeatherRequest
	(*GetWeatherResponse)(nil), // 1: pb.GetWeatherResponse
	(*Weather)(nil),            // 2: pb.Weather
}
var file_rpc_get_weather_proto_depIdxs = []int32{
	2, // 0: pb.GetWeatherResponse.weather:type_name -> pb.Weather
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_weather_proto_init() }
func file_rpc_get_weather_proto_init() {
	if File_rpc_get_weather_proto != nil {
		return
	}
	file_weather_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_weather_proto_rawDesc), len(file_rpc_get_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_weather_proto_goTypes,
		DependencyIndexes: file_rpc_get_weather_proto_depIdxs,
		MessageInfos:      file_rpc_get_weather_proto_msgTypes,
	}.Build()
	File_rpc_get_weather_proto = out.File
	file_rpc_get_weather_proto_goTypes = nil
	file_rpc_get_weather_proto_depIdxs = nil
}
