// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service_weather_app.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_weather_app_proto protoreflect.FileDescriptor

const file_service_weather_app_proto_rawDesc = "" +
	"\n" +
	"\x19service_weather_app.proto\x12\x02pb\x1a\x15rpc_get_weather.proto\x1a\x1drpc_create_subscription.proto2\x9e\x01\n" +
	"\n" +
	"WeatherApp\x12;\n" +
	"\n" +
	"GetWeather\x12\x15.pb.GetWeatherRequest\x1a\x16.pb.GetWeatherResponse\x12S\n" +
	"\x12CreateSubscription\x12\x1d.pb.CreateSubscriptionRequest\x1a\x1e.pb.CreateSubscriptionResponseB'Z%github.com/kirildevops/weather-api/pbb\x06proto3"

var file_service_weather_app_proto_goTypes = []any{
	(*GetWeatherRequest)(nil),          // 0: pb.GetWeatherRequest
	(*CreateSubscriptionRequest)(nil),  // 1: pb.CreateSubscriptionRequest
	(*GetWeatherResponse)(nil),         // 2: pb.GetWeatherResponse
	(*CreateSubscriptionResponse)(nil), // 3: pb.CreateSubscriptionResponse
}
var file_service_weather_app_proto_depIdxs = []int32{
	0, // 0: pb.WeatherApp.GetWeather:input_type -> pb.GetWeatherRequest
	1, // 1: pb.WeatherApp.CreateSubscription:input_type -> pb.CreateSubscriptionRequest
	2, // 2: pb.WeatherApp.GetWeather:output_type -> pb.GetWeatherResponse
	3, // 3: pb.WeatherApp.CreateSubscription:output_type -> pb.CreateSubscriptionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_weather_app_proto_init() }
func file_service_weather_app_proto_init() {
	if File_service_weather_app_proto != nil {
		return
	}
	file_rpc_get_weather_proto_init()
	file_rpc_create_subscription_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_weather_app_proto_rawDesc), len(file_service_weather_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_weather_app_proto_goTypes,
		DependencyIndexes: file_service_weather_app_proto_depIdxs,
	}.Build()
	File_service_weather_app_proto = out.File
	file_service_weather_app_proto_goTypes = nil
	file_service_weather_app_proto_depIdxs = nil
}
