// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: subscription.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frequency int32

const (
	Frequency_FREQUENCY_UNSPECIFIED Frequency = 0
	Frequency_FREQUENCY_hourly      Frequency = 1
	Frequency_FREQUENCY_HOURLY      Frequency = 1
	Frequency_FREQUENCY_daily       Frequency = 2
	Frequency_FREQUENCY_DAILY       Frequency = 2
)

// Enum value maps for Frequency.
var (
	Frequency_name = map[int32]string{
		0: "FREQUENCY_UNSPECIFIED",
		1: "FREQUENCY_hourly",
		// Duplicate value: 1: "FREQUENCY_HOURLY",
		2: "FREQUENCY_daily",
		// Duplicate value: 2: "FREQUENCY_DAILY",
	}
	Frequency_value = map[string]int32{
		"FREQUENCY_UNSPECIFIED": 0,
		"FREQUENCY_hourly":      1,
		"FREQUENCY_HOURLY":      1,
		"FREQUENCY_daily":       2,
		"FREQUENCY_DAILY":       2,
	}
)

func (x Frequency) Enum() *Frequency {
	p := new(Frequency)
	*p = x
	return p
}

func (x Frequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Frequency) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_proto_enumTypes[0].Descriptor()
}

func (Frequency) Type() protoreflect.EnumType {
	return &file_subscription_proto_enumTypes[0]
}

func (x Frequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Frequency.Descriptor instead.
func (Frequency) EnumDescriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Frequency     Frequency              `protobuf:"varint,3,opt,name=frequency,proto3,enum=pb.Frequency" json:"frequency,omitempty"`
	Confirmed     bool                   `protobuf:"varint,4,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Subscription) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Subscription) GetFrequency() Frequency {
	if x != nil {
		return x.Frequency
	}
	return Frequency_FREQUENCY_UNSPECIFIED
}

func (x *Subscription) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\x02pb\"\x83\x01\n" +
	"\fSubscription\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12+\n" +
	"\tfrequency\x18\x03 \x01(\x0e2\r.pb.FrequencyR\tfrequency\x12\x1c\n" +
	"\tconfirmed\x18\x04 \x01(\bR\tconfirmed*\x80\x01\n" +
	"\tFrequency\x12\x19\n" +
	"\x15FREQUENCY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FREQUENCY_hourly\x10\x01\x12\x14\n" +
	"\x10FREQUENCY_HOURLY\x10\x01\x12\x13\n" +
	"\x0fFREQUENCY_daily\x10\x02\x12\x13\n" +
	"\x0fFREQUENCY_DAILY\x10\x02\x1a\x02\x10\x01B'Z%github.com/kirildevops/weather-api/pbb\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_subscription_proto_goTypes = []any{
	(Frequency)(0),       // 0: pb.Frequency
	(*Subscription)(nil), // 1: pb.Subscription
}
var file_subscription_proto_depIdxs = []int32{
	0, // 0: pb.Subscription.frequency:type_name -> pb.Frequency
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		EnumInfos:         file_subscription_proto_enumTypes,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
