// Code generated by go-swagger; DO NOT EDIT.

package weather

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetWeatherParams creates a new GetWeatherParams object
//
// There are no default values defined in the spec.
func NewGetWeatherParams() GetWeatherParams {

	return GetWeatherParams{}
}

// GetWeatherParams contains all the bound params for the get weather operation
// typically these are obtained from a http.Request
//
// swagger:parameters getWeather
type GetWeatherParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*City name for weather forecast
	  Required: true
	  In: query
	*/
	City string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWeatherParams() beforehand.
func (o *GetWeatherParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCity, qhkCity, _ := qs.GetOK("city")
	if err := o.bindCity(qCity, qhkCity, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCity binds and validates parameter City from query.
func (o *GetWeatherParams) bindCity(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("city", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("city", "query", raw); err != nil {
		return err
	}
	o.City = raw

	return nil
}
