// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Weather weather
//
// swagger:model Weather
type Weather struct {

	// Weather description
	Description string `json:"description,omitempty"`

	// Current humidity percentage
	Humidity float64 `json:"humidity,omitempty"`

	// Current temperature
	Temperature float64 `json:"temperature,omitempty"`
}

// Validate validates this weather
func (m *Weather) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this weather based on context it is used
func (m *Weather) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Weather) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Weather) UnmarshalBinary(b []byte) error {
	var res Weather
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
